name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: |-
          curl https://www.fixmystreet.com/open311/v2/requests.json?jurisdiction_id=fixmystreet&status=open&agency_responsible=2492 | jq . > fixmystreet-open-cases.json
      - name: Save as csv
        run: |-
          deno run --allow-read --allow-write --allow-run --unstable postprocess.ts
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
